services:
  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "5001:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
